"use client";

/**
 * PANG — deep-zoom smoke client.
 *
 * Minimal surface. Exposes two affordances:
 *
 *   - "open"  — writes `activeDeepZoom` so the connector mounts.
 *   - "close" — writes `activeDeepZoom = null` (Escape / the
 *               connector's own close button does the same thing).
 *
 * A single seeded fixture lives at `/vendor/deepzoom/sample.png`
 * (generated by `scripts/seed-deepzoom-fixture.mjs`, checked into
 * the repo). Simple-image tile source in v1; a DZI manifest joins
 * here when the tile pipeline iteration ships.
 *
 * Playwright hooks itself into the connector via the public
 * `window.__PANG.useWorks` seam (installed by `AppBoot` behind the
 * same env flag that gates this route). The spec seeds
 * `activeDeepZoom` directly, observes the mount, Escape-closes,
 * and measures heap delta across 10 cycles.
 */

import { useState, type ReactElement } from "react";
import {
  DeepZoomConnector,
  type DeepZoomSource,
} from "@/components/deep-zoom/DeepZoom";
import { useWorks } from "@/stores/works";
import { DEEP_ZOOM_SMOKE } from "@/ai/smoke/voice";

const SAMPLE_WORK_ID = "smoke-sample";
const SAMPLE_FILE_REF = "vendor/deepzoom/sample.png";
const SAMPLE_COMPOSITE = `${SAMPLE_WORK_ID}:${SAMPLE_FILE_REF}`;

function resolve(workId: string, fileRef: string): DeepZoomSource | null {
  if (workId !== SAMPLE_WORK_ID) return null;
  if (fileRef !== SAMPLE_FILE_REF) return null;
  return { kind: "simple-image", url: "/vendor/deepzoom/sample.png" };
}

export function DeepZoomSmokeClient(): ReactElement {
  const [cycles, setCycles] = useState(0);
  return (
    <div className="relative h-full w-full">
      <div className="absolute inset-0 flex flex-col items-center justify-center gap-4 p-6">
        <p className="text-xs uppercase tracking-wide text-ink-ai">
          {DEEP_ZOOM_SMOKE.header}
        </p>
        <div className="flex gap-3">
          <button
            type="button"
            data-testid="deep-zoom-open"
            onClick={() => {
              useWorks.getState().setActiveDeepZoom(SAMPLE_COMPOSITE);
              setCycles((c) => c + 1);
            }}
            className="px-3 py-2 text-xs uppercase tracking-wide text-ink-ai"
          >
            {DEEP_ZOOM_SMOKE.open}
          </button>
          <button
            type="button"
            data-testid="deep-zoom-close"
            onClick={() => useWorks.getState().setActiveDeepZoom(null)}
            className="px-3 py-2 text-xs uppercase tracking-wide text-ink-ai"
          >
            {DEEP_ZOOM_SMOKE.close}
          </button>
        </div>
        <p
          className="text-xs text-ink-ai"
          data-testid="deep-zoom-cycles"
        >
          {DEEP_ZOOM_SMOKE.cycles_label} {cycles}
        </p>
      </div>
      <DeepZoomConnector resolve={resolve} />
    </div>
  );
}
